Make scripts more DRY

diff --git a/bachatalinux-builder/usr/sbin/bachatalinux-bundle b/bachatalinux-builder/usr/sbin/bachatalinux-bundle
--- a/bachatalinux-builder/usr/sbin/bachatalinux-bundle
+++ b/bachatalinux-builder/usr/sbin/bachatalinux-bundle
@@ -25,7 +25,7 @@ usage()
 	cat <<EOT
       --help                   display this help and exit
       --mirror=MIRROR          Debian mirror URL, see http://www.debian.org/mirror/list (required)
-      --kernel=pkg             kernel package to install (default: linux-image-686)
+      --kernel=kernel          kernel to install
       --include-apt=pkg1,pkg2  additional packages to install using APT, will automatically install dependencies
       --include-deb=filename   additional packages to install from .deb file (can be repeated), will NOT install dependencies
 EOT
@@ -41,29 +41,31 @@ while true ; do
 	case "$1" in
 		--help) usage ;;
 		--mirror) MIRROR="$2" ; shift 2 ;;
-		--kernel) KERNEL_PKG=",$2" ; shift 2 ;;
+        --kernel) KERNEL="$2" ; shift 2 ;;
 		--include-apt) INCLUDE_APT="${INCLUDE_APT},$2" ; shift 2 ;;
 		--include-deb) INCLUDE_DEB="${INCLUDE_DEB} $2" ; shift 2 ;;
 		--) shift ; break ;;
-		*) echo "Internal error!" ; exit 1 ;;
+		*) echo "Internal error: $1" ; exit 1 ;;
 	esac
 done
 if [ ! ${MIRROR} ]; then usage; fi
-if [ ! ${KERNEL_PKG} ]; then KERNEL_PKG=",linux-image-686"; fi
+if [ ! ${KERNEL} ]; then usage; fi
 
 if [ `id -u` -ne 0 ]; then
 	echo "You must be root"
 	exit 1
 fi
 
-echo "Creating Bachata Linux bundle..."
+echo "Creating Bachata Linux ${VERSION} bundle for ${ARCH} with kernel ${KERNEL}..."
 
 PWD=`pwd`
 TARGET=`mktemp -d --tmpdir=${PWD}`
 
 INCLUDE_DEB="${INCLUDE_DEB} /usr/share/bachatalinux-builder/localepurge-tiny_1.0_all.deb"
 
-debootstrap --variant=minbase --include=netbase,ifupdown,net-tools,isc-dhcp-client,acpi-support-base,acpid${KERNEL_PKG}${INCLUDE_APT} squeeze ${TARGET} ${MIRROR}
+debootstrap --variant=minbase \
+    --include=netbase,ifupdown,net-tools,isc-dhcp-client,acpi-support-base,acpid,linux-image-${KERNEL},${INCLUDE_APT} \
+    squeeze ${TARGET} ${MIRROR}
 if [ $? != 0 ]; then
     echo "Installation failed!"
     exit 1
@@ -79,9 +81,7 @@ wq
 EOT
 
 for deb in ${INCLUDE_DEB}; do
-    cp ${deb} ${TARGET}/var/cache/apt/archives
-    chroot ${TARGET} dpkg -i /var/cache/apt/archives/`basename ${deb}`
-    rm ${TARGET}/var/cache/apt/archives/`basename ${deb}`
+    dpkg --root=${TARGET} -i ${deb}
 done
 
 rm -rf ${TARGET}/usr/share/man/*
@@ -163,7 +163,7 @@ EOT
 
 chroot ${TARGET} localepurge-tiny
 
-BUNDLE="bachatalinux-${VERSION}-${ARCH}.cgz"
+BUNDLE="bachatalinux-${VERSION}-${ARCH}-${KERNEL}.cgz"
 
 (cd ${TARGET} && find . -type l -printf '%p %Y\n' | sed -n 's/ [LN]$//p' | xargs -rL1 rm -f)
 (cd ${TARGET} && find . | cpio --quiet -o -H newc | gzip -9) >${BUNDLE}
diff --git a/bachatalinux-builder/usr/sbin/bachatalinux-media b/bachatalinux-builder/usr/sbin/bachatalinux-media
--- a/bachatalinux-builder/usr/sbin/bachatalinux-media
+++ b/bachatalinux-builder/usr/sbin/bachatalinux-media
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Build a Bachata Linux install disk image
+# Build a Bachata Linux install media image
 # Copyright (C) 2012 Mikael Ståldal
 
 # This program is free software: you can redistribute it and/or modify
@@ -25,12 +25,13 @@ usage()
 	cat <<EOT
       --help                   display this help and exit
       --mirror=MIRROR          Debian mirror URL, see http://www.debian.org/mirror/list (required)
-      --bundle=bundle.cgz      bundle to use
+      --kernel=kernel          kernel to install
+      --cdrom                  build CD-ROM image
 EOT
     exit 1
 }
 
-OPTIONS=`getopt --options "" --longoptions help,mirror:,bundle: -n 'bachatalinux-disk' -- "$@"`
+OPTIONS=`getopt --options "" --longoptions help,mirror:,kernel:,cdrom -n 'bachatalinux-media' -- "$@"`
 if [ $? != 0 ]; then
     exit 1
 fi
@@ -39,16 +40,17 @@ while true ; do
 	case "$1" in
 		--help) usage ;;
 		--mirror) MIRROR="$2" ; shift 2 ;;
-		--bundle) BUNDLE="$2" ; shift 2 ;;
+        --kernel) KERNEL="$2" ; shift 2 ;;
+		--cdrom) CDROM=true ; shift 1 ;;
 		--) shift ; break ;;
-		*) echo "Internal error!" ; exit 1 ;;
+		*) echo "Internal error: $1" ; exit 1 ;;
 	esac
 done
 
 if [ ! ${MIRROR} ]; then usage; fi
-if [ ! ${BUNDLE} ]; then 
-    BUNDLE="bachatalinux-${VERSION}-${ARCH}.cgz"
-fi
+if [ ! ${KERNEL} ]; then usage; fi
+
+BUNDLE="bachatalinux-${VERSION}-${ARCH}-${KERNEL}.cgz"
 
 if [ ! -f ${BUNDLE} ]; then
     echo "Cannot find ${BUNDLE}"
@@ -60,22 +62,29 @@ if [ `id -u` -ne 0 ]; then
 	exit 1
 fi
 
-echo "Creating Bachata Linux install disk..."
-
-DISK_IMAGE="bachatalinux-${VERSION}-${ARCH}.img"
-
-dd if=/dev/zero of=${DISK_IMAGE} bs=80M count=1
-
-mke2fs -F -L "BachataLinux" -t ext2 ${DISK_IMAGE}
-IMAGE_FS=`mktemp -d`
-mount -t ext2 ${DISK_IMAGE} ${IMAGE_FS}
-if [ $? != 0 ] ; then
-    exit 2
-fi
+echo "Creating Bachata Linux ${VERSION} install media for ${ARCH} with kernel ${KERNEL}..."
 
 PWD=`pwd`
+IMAGE_FS=`mktemp -d --tmpdir=${PWD}`
 
-mkdir -p ${IMAGE_FS}/boot/extlinux
+if [ ${CDROM} ]; then
+    DISK_IMAGE="bachatalinux-${VERSION}-${ARCH}-${KERNEL}.iso"
+    FSTYPE="iso9660"
+    BOOT_DIR=${IMAGE_FS}/isolinux
+    chmod 0555 ${IMAGE_FS}
+    mkdir ${BOOT_DIR}
+else
+    DISK_IMAGE="bachatalinux-${VERSION}-${ARCH}-${KERNEL}.img"
+    FSTYPE="ext2"
+    BOOT_DIR=${IMAGE_FS}/boot
+    dd if=/dev/zero of=${DISK_IMAGE} bs=1M count=120
+    mke2fs -F -L "BachataLinux" -t ext2 ${DISK_IMAGE}
+    mount -t ext2 ${DISK_IMAGE} ${IMAGE_FS}
+    if [ $? != 0 ] ; then
+        exit 2
+    fi
+    mkdir -p ${BOOT_DIR}/extlinux
+fi
 
 cp ${BUNDLE} ${IMAGE_FS}/bachatalinux.cgz
 
@@ -83,7 +92,10 @@ INSTALL_FS=`mktemp -d --tmpdir=${PWD}`
 
 gzip -cd <${BUNDLE} | (cd ${INSTALL_FS} && cpio -i --quiet)
 
-cp ${INSTALL_FS}/boot/vmlinuz-* ${IMAGE_FS}/boot/vmlinuz
+debootstrap --variant=minbase \
+	--include=extlinux,syslinux-common,eject squeeze ${INSTALL_FS} ${MIRROR}
+
+cp ${INSTALL_FS}/boot/vmlinuz-* ${BOOT_DIR}/vmlinuz
 
 ROOT_FS=`mktemp -d --tmpdir=${PWD}`
 
@@ -105,11 +117,9 @@ cp ${INSTALL_FS}/lib/libtic.so.5.7 ${ROOT_FS}/lib/
 (cd ${ROOT_FS}/lib && ln -s libtic.so.5.7 libtic.so.5)
 cp ${INSTALL_FS}/lib/libcom_err.so.2.1 ${ROOT_FS}/lib/
 (cd ${ROOT_FS}/lib && ln -s libcom_err.so.2.1 libcom_err.so.2)
-cp ${INSTALL_FS}/lib/libpthread-2.11.2.so ${ROOT_FS}/lib/
-(cd ${ROOT_FS}/lib && ln -s libpthread-2.11.2.so libpthread.so.0)
+cp ${INSTALL_FS}/lib/libpthread-2.11.3.so ${ROOT_FS}/lib/
+(cd ${ROOT_FS}/lib && ln -s libpthread-2.11.3.so libpthread.so.0)
 
-debootstrap --variant=minbase --no-resolve-deps \
-	--include=extlinux,syslinux-common,eject squeeze ${INSTALL_FS} ${MIRROR}
 cp ${INSTALL_FS}/usr/sbin/extlinux ${ROOT_FS}/sbin/
 cp ${INSTALL_FS}/usr/lib/syslinux/mbr.bin ${ROOT_FS}/lib/
 cp ${INSTALL_FS}/usr/bin/eject ${ROOT_FS}/bin/
@@ -122,6 +132,8 @@ cp /usr/share/bachatalinux-builder/install-bachatalinux ${ROOT_FS}/sbin/
 chmod +x ${ROOT_FS}/sbin/install-bachatalinux
 cp /usr/share/bachatalinux-builder/install-bachatalinux ${IMAGE_FS}/
 chmod +x ${IMAGE_FS}/install-bachatalinux
+cp /usr/share/bachatalinux-builder/install-bachatalinux-in-kvm-qemu ${IMAGE_FS}/
+chmod +x ${IMAGE_FS}/install-bachatalinux-in-kvm-qemu
 
 cat <<EOT |ed -s ${ROOT_FS}/init >/dev/null
 /Loading, please wait/
@@ -129,7 +141,7 @@ s/^/# /
 /maybe_break premount/
 ;d
 a
-exec /sbin/install-bachatalinux-from-media ext2
+exec /sbin/install-bachatalinux-from-media ${FSTYPE}
 .
 wq
 EOT
@@ -140,33 +152,50 @@ mkdir ${ROOT_FS}/mnt
 touch ${ROOT_FS}/etc/mtab
 
 (cd ${ROOT_FS} && find . -type l -printf '%p %Y\n' | sed -n 's/ [LN]$//p' | xargs -rL1 rm -f)
-(cd ${ROOT_FS} && find . | cpio --quiet -R 0:0 -o -H newc | gzip -9) >${IMAGE_FS}/boot/initrd.img
+(cd ${ROOT_FS} && find . | cpio --quiet -R 0:0 -o -H newc | gzip -9) >${BOOT_DIR}/initrd.img
 
 rm -rf -- ${ROOT_FS}
 
-extlinux --install ${IMAGE_FS}/boot/extlinux
+if [ ${CDROM} ]; then
+    cp /usr/lib/syslinux/isolinux.bin ${IMAGE_FS}/isolinux/
 
-cat <<EOT >${IMAGE_FS}/boot/extlinux/syslinux.cfg
+    cat <<EOT >${IMAGE_FS}/isolinux/isolinux.cfg
+default linux
+label linux
+    kernel vmlinuz
+    append initrd=initrd.img quiet
+EOT
+else
+    extlinux --install ${IMAGE_FS}/boot/extlinux
+
+    cat <<EOT >${IMAGE_FS}/boot/extlinux/syslinux.cfg
 default linux
 label linux
     kernel /boot/vmlinuz
     append initrd=/boot/initrd.img quiet
 EOT
+fi
 
 cat <<EOT >${IMAGE_FS}/README
-Bachata Linux ${VERSION} for ${ARCH} (based on Debian GNU/Linux 6.0)
+Bachata Linux ${VERSION} for ${ARCH} with kernel ${KERNEL} (based on Debian GNU/Linux 6.0)
 
  * Home page: http://www.bachatalinux.net/
 
-Install Bachata Linux by booting from this bootable disk.
+Install Bachata Linux by booting from this bootable medium.
 Or if you are already running a Linux system you may try to run 
-the script install_bachatalinux as root.
+the script install-bachatalinux as root.
 EOT
 
-sleep 1
-umount ${IMAGE_FS}
+if [ ${CDROM} ]; then
+    genisoimage -o "${DISK_IMAGE}" -b isolinux/isolinux.bin -c isolinux/boot.cat \
+        -no-emul-boot -boot-load-size 4 -boot-info-table -l -R -input-charset default \
+        -V BachataLinux -A "Bachata Linux" ${IMAGE_FS}
+else
+    sleep 1
+    umount ${IMAGE_FS}
+fi
 
-rmdir -- ${IMAGE_FS}
+rm -rf -- ${IMAGE_FS}
 
-echo "Finished generating disk image ${DISK_IMAGE}"
+echo "Finished generating image ${DISK_IMAGE}"
 
